In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/NLP/test.txt', sep= ';', header= None, names = ['text','emotion'])

In [35]:
df.head()

                                                text  emotion
0  im feeling rather rotten so im not very ambiti...  sadness
1          im updating my blog because i feel shitty  sadness
2  i never make her separate from me because i do...  sadness
3  i left with my bouquet of red and yellow tulip...      joy
4    i was feeling a little vain when i did this one  sadness

In [36]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [37]:
unique_emotions = df['emotion'].unique()

In [38]:
emotion_numbers = {}
i = 0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i += 1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [39]:
df

                                                   text  emotion
0     im feeling rather rotten so im not very ambiti...        0
1             im updating my blog because i feel shitty        0
2     i never make her separate from me because i do...        0
3     i left with my bouquet of red and yellow tulip...        1
4       i was feeling a little vain when i did this one        0
...                                                 ...      ...
1995  i just keep feeling like someone is being unki...        3
1996  im feeling a little cranky negative after this...        3
1997  i feel that i am useful to my people and that ...        1
1998  im feeling more comfortable with derby i feel ...        1
1999  i feel all weird when i have to meet w people ...        2

[2000 rows x 2 columns]

In [40]:
df['text'] = df['text'].apply(lambda x: x.lower())

In [41]:
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [42]:
df['text'] = df['text'].apply(remove_punc)

In [43]:
def remove_numbers(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new = new + i
  return new

df['text'] = df['text'].apply(remove_numbers)

In [44]:
def remove_emojis(txt):
  new = ""
  for i in txt:
    if i.isascii():
      new += i
  return new

df['text'] = df['text'].apply(remove_emojis)

In [45]:
import nltk

In [46]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [47]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [48]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [49]:
df.loc[1]['text']

'im updating my blog because i feel shitty'

In [50]:
def remove(txt):
  words = txt.split()
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)
  return ' '.join(cleaned)

In [51]:
df['text'] = df['text'].apply(remove)

In [52]:
df.loc[1]['text']

'im updating blog feel shitty'

In [53]:
df.head()

                                                text  emotion
0        im feeling rather rotten im ambitious right        0
1                       im updating blog feel shitty        0
2    never make separate ever want feel like ashamed        0
3  left bouquet red yellow tulips arm feeling sli...        1
4                            feeling little vain one        0

In [54]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [55]:

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)


pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

0.615

In [56]:
pred_bow

array([0, 1, 1, 3, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 3, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 2, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 3, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 3, 0, 0, 3, 2, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 4,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 3, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       3, 1, 0, 2, 1, 1, 2, 1, 1, 3, 0, 1, 3, 2, 3, 0, 0, 3, 1, 1, 3, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 2, 0,
       3, 0, 1, 2, 1, 0, 0, 0, 1, 0, 2, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 3,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 3, 0,
       0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 1, 1, 0, 3,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1])

In [57]:


tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [58]:
y_pred = nb2_model.predict(X_test_tfidf)

In [59]:
print(accuracy_score(y_test, y_pred))

0.575

In [60]:
from sklearn.linear_model import LogisticRegression

In [61]:
logistic_model = LogisticRegression(max_iter=1000)

In [62]:
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [63]:
log_pred = logistic_model.predict(X_test_tfidf)

In [64]:
print(accuracy_score(y_test,log_pred ))

0.6375